### ISSUE TITLE
Invariant Violation: requireNativeComponent: "RNSVGLinearGradient" was not found in the UIManager.

### ISSUE THREAD

**Issue by Flaviano-Rodrigues** [Expensify/react-native-qrcode-svg#198]
![image](https://github.com/awesomejerry/react-native-qrcode-svg/assets/112655909/448ff643-7c35-4550-b7e8-53a9ddd4b49f)

```javascript
import React from "react"
import { View } from "react-native"
import QRCode from "react-native-qrcode-svg"

interface Props {
  value: string
}

const QrCode: React.ElementType<Props> = ({ value }: Props) => {

  return (
    <View style={{ justifyContent: 'center', alignItems: 'center' }}>
      <QRCode
        value={value}
        size={300}
        logo={require('../../../assets/favicon.png')}
      />
    </View>
  )
}


export default QrCode

``` 

"expo": "^51.0.17",
"react": "18.2.0",
"react-native": "^0.74.3",
"react-native-qrcode-svg": "^6.3.1",
"react-native-svg": "^15.3.0",

**Comment by DevWonder01** [comment]
For me I installed following this package for generating QR CODES.

npm install react-native-qrcode-sv
But above package is dependent on the bellow package

npm install react-native-svg
when i installed react-native-svg my app, I then ran npx react-native run-android to rebuild the  app


it's works great now

![image](https://github.com/user-attachments/assets/14d8367d-63f1-4520-bc20-7991da9b344b)

**Comment by Flaviano-Rodrigues** [comment]
> npm install react-native-svg

That works!

react-native-svg released a new version yesterday. With 15.4.0 it worked. 
Thanks
