### ISSUE TITLE
Property 'TextEncoder' doesn't exist

### ISSUE THREAD

**Issue by syuanlj** [Expensify/react-native-qrcode-svg#199]
![image](https://github.com/user-attachments/assets/8f30b42a-55af-4074-9df8-56a9be89035f)

**Comment by ashindiano** [comment]
I am facing the same issue too

**Comment by ZaurRza** [comment]
same error

**Comment by farm16** [comment]
@syuanlj  same here, but can you provide more info regarding which version you are using. also the output of `npx react-native info` can help

**Comment by osamaabdalla** [comment]
This solution worked for me:

1. First, install the `text-encoding` package by running the following command:
   ```bash
   npm install --save text-encoding
   ```

2. Then, import it into the file where you are using the QRCode:
   ```javascript
   import 'text-encoding';
   ```

this is influenced by: https://github.com/facebook/hermes/issues/948#issuecomment-1484240071

**Comment by 12ya** [comment]
created a pull request.
who can't wait for merge just change this in package.json
`"react-native-qrcode-svg": "https://github.com/12ya/react-native-qrcode-svg" `

**Comment by syuanlj** [comment]
> This solution worked for me:
> 
> 1. First, install the `text-encoding` package by running the following command:
>    ```shell
>    npm install --save text-encoding
>    ```
> 2. Then, import it into the file where you are using the QRCode:
>    ```js
>    import 'text-encoding';
>    ```
> 
> this is influenced by: [facebook/hermes#948 (comment)](https://github.com/facebook/hermes/issues/948#issuecomment-1484240071)

**Comment by syuanlj** [comment]
> This solution worked for me:
> 
> 1. First, install the `text-encoding` package by running the following command:
>    ```shell
>    npm install --save text-encoding
>    ```
> 2. Then, import it into the file where you are using the QRCode:
>    ```js
>    import 'text-encoding';
>    ```
> 
> this is influenced by: [facebook/hermes#948 (comment)](https://github.com/facebook/hermes/issues/948#issuecomment-1484240071)

**Comment by urvindevstree** [comment]
This solution worked for me:

Navigate to _node_module/qrcode/lib/core/byte-data.js_ file.

1. Please update below line : 
`this.data = new TextEncoder().encode(data)` to `this.data = stringToUtf8Uint8Array(data)`.

2. Add this function in same file :
```Javascript
function stringToUtf8Uint8Array(str) {
  const utf8 = encodeURIComponent(str)
    .replace(/%([0-9A-F]{2})/g, (_, p1) => String.fromCharCode('utf-8'));
  const arr = new Uint8Array(utf8.length);
  for (let i = 0; i < utf8.length; i++) {
    arr[i] = utf8.charCodeAt(i);
  }
  return arr;
}
```

**Comment by arnoldosilva** [comment]
this works for me 

add transformer on metro:

const { getDefaultConfig, mergeConfig } = require("@react-native/metro-config");

const defaultConfig = getDefaultConfig(__dirname);

const config = {
  transformer: {
    babelTransformerPath: require.resolve("react-native-qrcode-svg/textEncodingTransformation"),
  },
};

module.exports = mergeConfig(defaultConfig, config);

**Comment by LeaderBoard-Jacob** [comment]
> This solution worked for me:
> 
> Navigate to _node_module/qrcode/lib/core/byte-data.js_ file.
> 
> 1. Please update below line :
>    `this.data = new TextEncoder().encode(data)` to `this.data = stringToUtf8Uint8Array(data)`.
> 2. Add this function in same file :
> 
> function stringToUtf8Uint8Array(str) {
>   const utf8 = encodeURIComponent(str)
>     .replace(/%([0-9A-F]{2})/g, (_, p1) => String.fromCharCode('utf-8'));
>   const arr = new Uint8Array(utf8.length);
>   for (let i = 0; i < utf8.length; i++) {
>     arr[i] = utf8.charCodeAt(i);
>   }
>   return arr;
> }

Unfortunately, this solution doesn't seem to work for certain characters that are essential to a url. `:` and `/` were parsed as `�`. I ran this solution through Chatgpt and was given the following modification that is working perfectly for my use case. I figured I might as well post here as this is probably where most people will land when trying to solve this issue.

```js
function stringToUtf8Uint8Array(str) {
  const utf8 = encodeURIComponent(str)
    .replace(/%([0-9A-F]{2})/g, (_, p1) => String.fromCharCode(parseInt(p1, 16)));
  const arr = new Uint8Array(utf8.length);
  for (let i = 0; i < utf8.length; i++) {
    arr[i] = utf8.charCodeAt(i);
  }
  return arr;
}
```

**Comment by asapMaki** [comment]
For me this worked 

in your entry file(`index.js`) just paste the import on top, 
you can also use `import 'fast-text-encoding';` this lib is maintained
